name: postman
on:
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Setup Newman
        run: npm install -g newman
      - name: Running Postman Tests
        run: newman run ./treinamento.postman_collection.json --environment ./treinamento.postman_environment.json --insecure
      - name: Node version
        run: node -v
      - name: Newman version
        run: newman -v